In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
## One Hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[4831, 7064, 5685, 7051],
 [4831, 7064, 5685, 4670],
 [4831, 3936, 5685, 2002],
 [8667, 9427, 9528, 371, 2638],
 [8667, 9427, 9528, 371, 4723],
 [3684, 4831, 1433, 5685, 7290],
 [4587, 8237, 4646, 371]]

In [7]:
## word Embeddign Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4831 7064 5685 7051]
 [   0    0    0    0 4831 7064 5685 4670]
 [   0    0    0    0 4831 3936 5685 2002]
 [   0    0    0 8667 9427 9528  371 2638]
 [   0    0    0 8667 9427 9528  371 4723]
 [   0    0    0 3684 4831 1433 5685 7290]
 [   0    0    0    0 4587 8237 4646  371]]


In [9]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/shindesudeep/Desktop/GenAI_RLHF/ANN_env/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[ 0.02436132,  0.02511071,  0.03180376, -0.02888154,
         -0.01835046,  0.0430694 , -0.04221697,  0.03239033,
         -0.02249049, -0.03600627],
        [ 0.02436132,  0.02511071,  0.03180376, -0.02888154,
         -0.01835046,  0.0430694 , -0.04221697,  0.03239033,
         -0.02249049, -0.03600627],
        [ 0.02436132,  0.02511071,  0.03180376, -0.02888154,
         -0.01835046,  0.0430694 , -0.04221697,  0.03239033,
         -0.02249049, -0.03600627],
        [ 0.02436132,  0.02511071,  0.03180376, -0.02888154,
         -0.01835046,  0.0430694 , -0.04221697,  0.03239033,
         -0.02249049, -0.03600627],
        [-0.04234897,  0.01176528, -0.02097577, -0.00401518,
          0.01759144, -0.02692819,  0.03563296, -0.02054168,
         -0.04514624, -0.03986864],
        [ 0.02292857, -0.02566825, -0.03345682, -0.04866523,
         -0.02355274,  0.00248719, -0.02545257, -0.02558574,
          0.03794936,  0.04653421],
        [-0.0137329 ,  0.02166999, -0.00370574,  0.0